#https://github.com/carterword/repo-5.git

steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/carterword/repo-5.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t',  'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']

# kubectl set image deployment/cicd-app-1 repo-1-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
- name: 'gcr.io/cloud-builders/kubectl'
  args :
  - 'set'
  - 'image'
  - 'deployment/cicd-deployment-1'
  - 'repo-1-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}'
  env : 
  - 'CLOUDSDK_COMPUTE_ZONE=us-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'

substitutions:
  _PROJECT_ID : gcp-devops-436402
  _CINAME : gke-image
  _VERSION : v3.0

options:
  logging: CLOUD_LOGGING_ONLY
